#ifndef L2AUTH_L2_CLIENT_PACKET_TYPE_C
#define L2AUTH_L2_CLIENT_PACKET_TYPE_C

enum client_packet_type {
  CLIENT_PACKET_TYPE_REQUEST_AUTH_LOGIN = 0x00,
  CLIENT_PACKET_TYPE_GG_AUTH = 0x07
};

#endif //L2AUTH_L2_CLIENT_PACKET_TYPE_C