create table if not exists player_templates(
        class_id int,
        race_id int,
        str int,
        con int,
        dex int,
        _int int,
        wit int,
        men int,
        p_atk int,
        p_def int,
        m_atk int,
        m_def int,
        p_spd int,
        m_spd int,
        accuracy int,
        critical int,
        evasion int,
        walk_speed int,
        x int,
        y int,
        z int,
        can_craft int
);
