create table player_characters(
        account text primary key,
        state integer,
        id integer,
        name text,
        title text,
        hp float,
        mp float,
        max_hp float,
        max_mp float,
        cp integer,
        max_cp integer,
        level integer,
        clan_id integer,
        sex integer,
        race_id integer,
        class_id integer,
        x integer,
        y integer,
        z integer,
        sp integer,
        exp integer,
        karma integer,
        _int integer,
        str integer,
        con integer,
        men integer,
        dex integer,
        wit integer,
        p_attack integer,
        m_attack integer,
        p_def integer,
        m_def integer,
        evasion_rate integer,
        critical_hit integer
);
