#ifndef L2AUTH_GAME_REQUEST_VALIDATE_POSITION_NEXT_HANDLER_H
#define L2AUTH_GAME_REQUEST_VALIDATE_POSITION_NEXT_HANDLER_H

void* game_request_validate_position_next_handler(void* raw_request);

#endif
