#ifndef L2AUTH_GAME_PACKET_CLIENT_TYPE_H
#define L2AUTH_GAME_PACKET_CLIENT_TYPE_H

enum game_packet_client_type
{
        GAME_PACKET_CLIENT_TYPE_PROTOCOL_VERSION = 0x00,
        GAME_PACKET_CLIENT_TYPE_MOVE_BACKWARDS_TO_LOCATION = 0x01,
        GAME_PACKET_CLIENT_TYPE_AUTH_REQUEST = 0x08,
        GAME_PACKET_CLIENT_TYPE_NEW_CHAR = 0x0e,
        GAME_PACKET_CLIENT_TYPE_CREATE_CHAR = 0x0b,
        GAME_PACKET_CLIENT_TYPE_SELECTED_CHAR = 0x0d,
        GAME_PACKET_CLIENT_TYPE_REQUEST_AUTO_SS_BSPS = 0xd0,
        GAME_PACKET_CLIENT_TYPE_REQUEST_QUEST_LIST = 0x63,
        GAME_PACKET_CLIENT_TYPE_ENTER_WORLD = 0x03,
        GAME_PACKET_CLIENT_TYPE_RESTART = 0x46,
        GAME_PACKET_CLIENT_TYPE_VALIDATE_POS = 0x48
};

#endif
