#ifndef L2AUTH_GAME_PACKET_CLIENT_TYPE_H
#define L2AUTH_GAME_PACKET_CLIENT_TYPE_H

enum game_packet_client_type
{
        GAME_PACKET_CLIENT_TYPE_PROTOCOL_VERSION = 0x00,
        GAME_PACKET_CLIENT_TYPE_AUTH_REQUEST = 0x08
};

#endif
