#ifndef LIB_CLIENT_PACKET_TYPE_H
#define LIB_CLIENT_PACKET_TYPE_H

/**
 * All packet types sent by
 * the Lineage 2 client.
 */
enum ClientPacketType
{
        CLIENT_PACKET_TYPE_PROTOCOL_VERSION = 0x00,
        CLIENT_PACKET_TYPE_MOVE_BACKWARDS_TO_LOCATION = 0x01,
        CLIENT_PACKET_TYPE_ACTION = 0x04,
        CLIENT_PACKET_TYPE_AUTH_REQUEST = 0x08,
        CLIENT_PACKET_TYPE_NEW_CHAR = 0x0e,
        CLIENT_PACKET_TYPE_CREATE_CHAR = 0x0b,
        CLIENT_PACKET_TYPE_SELECTED_CHAR = 0x0d,
        CLIENT_PACKET_TYPE_REQUEST_AUTO_SS_BSPS = 0xd0,
        CLIENT_PACKET_TYPE_REQUEST_QUEST_LIST = 0x63,
        CLIENT_PACKET_TYPE_ENTER_WORLD = 0x03,
        CLIENT_PACKET_TYPE_RESTART = 0x46,
        CLIENT_PACKET_TYPE_VALIDATE_POS = 0x48,
        CLIENT_PACKET_TYPE_SAY = 0x38,
        CLIENT_PACKET_TYPE_LOGOUT = 0x09,
        CLIENT_PACKET_TYPE_SHOW_MAP = 0xcd
};

#endif
