#ifndef INCLUDE_GS_PACKET_ENTER_WORLD_H
#define INCLUDE_GS_PACKET_ENTER_WORLD_H

#include "util.h"
#include "l2_string.h"
#include "packet.h"
#include "gs_character.h"

typedef struct {
        i32_t x;
        i32_t y;
        i32_t z;
        i32_t heading;
        u32_t id;
        l2_string_t name[28];
        u32_t race_id;
        u32_t sex;
        u32_t class_id;
        u32_t level;
        u32_t exp;
        i32_t str;
        i32_t dex;
        i32_t con;
        i32_t _int;
        i32_t wit;
        i32_t men;
        u32_t max_hp;
        u32_t hp;
        u32_t max_mp;
        u32_t mp;
        u32_t sp;
        i32_t current_load;
        i32_t max_load;
        i32_t unknown;
        i32_t paperdoll_under;
        i32_t paperdoll_r_ear;
        i32_t paperdoll_l_ear;
        i32_t paperdoll_neck;
        i32_t paperdoll_r_finger;
        i32_t paperdoll_l_finger;
        i32_t paperdoll_head;
        i32_t paperdoll_r_hand;
        i32_t paperdoll_l_hand;
        i32_t paperdoll_gloves;
        i32_t paperdoll_chest;
        i32_t paperdoll_legs;
        i32_t paperdoll_feet;
        i32_t paperdoll_back;
        i32_t paperdoll_lr_hand;
        i32_t paperdoll_hair;
        i32_t empty[16];
        u32_t p_attack;
        u32_t p_attack_speed;
        u32_t p_def;
        u32_t evasion_rate;
        u32_t accuracy;
        u32_t critical_hit;
        u32_t m_attack;
        u32_t m_attack_speed;
        u32_t p_attack_speed_copy;
        u32_t m_def;
        u32_t pvp;
        u32_t karma;
        u32_t run_speed;
        u32_t walk_speed;
        u32_t swim_run_speed;
        u32_t swim_walk_speed;
        u32_t fly_run_speed;
        u32_t fly_walk_speed;
        u32_t fly_run_speed_copy;
        u32_t fly_walk_speed_copy;
        double movement_speed_multiplier;
        double attack_speed_multiplier;
        double collision_radius;
        double collision_height;
        u32_t hair_style_id;
        u32_t hair_color_id;
        u32_t face;
        i32_t access_level;
        l2_string_t title[28];
        u32_t clan_id;
        u32_t clan_crest_id;
        u32_t ally_id;
        u32_t ally_crest_id;
        u32_t clan_leader;
        u8_t mount_type;
        u8_t private_store_type;
        u8_t dwarven_craft;
        u32_t pk_kills;
        u32_t pvp_kills;
        u16_t cubics;
        u8_t party_members;
        i32_t abnormal_effect;
        u8_t char_empty[3];
        i32_t clan_privileges;
        i32_t int_empty[9];
        u16_t recommendation_left;
        u16_t recommendation_have;
        u16_t inventory_limit;
        u32_t class_id_copy;
        u32_t max_cp;
        u32_t cp;
        u8_t mounted;
        u32_t clan_crest_large_id;
        u8_t hero_symbol;
        u8_t hero;
        i32_t fish_x;
        i32_t fish_y;
        i32_t fish_z;
        u32_t name_color;
} gs_packet_enter_world_t;

void gs_packet_enter_world_set_char(
        gs_packet_enter_world_t *dest,
        gs_character_t *src);

void gs_packet_enter_world_pack(packet_t *dest, gs_packet_enter_world_t *src);

#endif
